#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define MAX 100
#define WORD_LEN 50
char undoStack[MAX][WORD_LEN];
char redoStack[MAX][WORD_LEN];
int topUndo = -1;
int topRedo = -1;
void pushUndo(char word[]){if(topUndo<MAX-1){topUndo++;strcpy(undoStack[topUndo],word);}}
void pushRedo(char word[]){if(topRedo<MAX-1){topRedo++;strcpy(redoStack[topRedo],word);}}
void clearRedoStack(){topRedo=-1;}
void saveToFile(){FILE *file=fopen("text_save.txt","w");if(file==NULL)return;for(int i=0;i<=topUndo;i++){fprintf(file,"%s ",undoStack[i]);}fclose(file);}
void loadFromFile(){FILE *file=fopen("text_save.txt","r");if(file==NULL)return;topUndo=-1;char word[WORD_LEN];while(fscanf(file,"%s",word)!=EOF){pushUndo(word);}fclose(file);}
void typeWord(){char word[WORD_LEN];printf("Enter word: ");scanf("%s",word);pushUndo(word);clearRedoStack();}
void undo(){if(topUndo>=0){pushRedo(undoStack[topUndo]);topUndo--;}}
void redo(){if(topRedo>=0){pushUndo(redoStack[topRedo]);topRedo--;}}
void showText(){printf("\nCurrent Text: ");for(int i=0;i<=topUndo;i++){printf("%s ",undoStack[i]);}printf("\n");}
void showUndoStack(){printf("\nUndo Stack: ");for(int i=0;i<=topUndo;i++){printf("%s ",undoStack[i]);}printf("\n");}
void showRedoStack(){printf("\nRedo Stack: ");for(int i=0;i<=topRedo;i++){printf("%s ",redoStack[i]);}printf("\n");}
void menu(){printf("\n--- Undo-Redo Text Editor ---\n");printf("1. Type a Word\n");printf("2. Undo\n");printf("3. Redo\n");printf("4. Show Current Text\n");printf("5. Show Undo Stack\n");printf("6. Show Redo Stack\n");printf("7. Save to File\n");printf("8. Load from File\n");printf("9. Exit\n");}
int main(){int choice;while(1){menu();printf("Enter your choice: ");scanf("%d",&choice);if(choice==1){typeWord();}else if(choice==2){undo();}else if(choice==3){redo();}else if(choice==4){showText();}else if(choice==5){showUndoStack();}else if(choice==6){showRedoStack();}else if(choice==7){saveToFile();}else if(choice==8){loadFromFile();}else if(choice==9){break;}else{printf("Invalid option\n");}}return 0;}
void fillerFunc22(){printf("Filler line 22\n");}
void fillerFunc23(){printf("Filler line 23\n");}
void fillerFunc24(){printf("Filler line 24\n");}
void fillerFunc25(){printf("Filler line 25\n");}
void fillerFunc26(){printf("Filler line 26\n");}
void fillerFunc27(){printf("Filler line 27\n");}
void fillerFunc28(){printf("Filler line 28\n");}
void fillerFunc29(){printf("Filler line 29\n");}
void fillerFunc30(){printf("Filler line 30\n");}
void fillerFunc31(){printf("Filler line 31\n");}
void fillerFunc32(){printf("Filler line 32\n");}
void fillerFunc33(){printf("Filler line 33\n");}
void fillerFunc34(){printf("Filler line 34\n");}
void fillerFunc35(){printf("Filler line 35\n");}
void fillerFunc36(){printf("Filler line 36\n");}
void fillerFunc37(){printf("Filler line 37\n");}
void fillerFunc38(){printf("Filler line 38\n");}
void fillerFunc39(){printf("Filler line 39\n");}
void fillerFunc40(){printf("Filler line 40\n");}
void fillerFunc41(){printf("Filler line 41\n");}
void fillerFunc42(){printf("Filler line 42\n");}
void fillerFunc43(){printf("Filler line 43\n");}
void fillerFunc44(){printf("Filler line 44\n");}
void fillerFunc45(){printf("Filler line 45\n");}
void fillerFunc46(){printf("Filler line 46\n");}
void fillerFunc47(){printf("Filler line 47\n");}
void fillerFunc48(){printf("Filler line 48\n");}
void fillerFunc49(){printf("Filler line 49\n");}
void fillerFunc50(){printf("Filler line 50\n");}
void fillerFunc51(){printf("Filler line 51\n");}
void fillerFunc52(){printf("Filler line 52\n");}
void fillerFunc53(){printf("Filler line 53\n");}
void fillerFunc54(){printf("Filler line 54\n");}
void fillerFunc55(){printf("Filler line 55\n");}
void fillerFunc56(){printf("Filler line 56\n");}
void fillerFunc57(){printf("Filler line 57\n");}
void fillerFunc58(){printf("Filler line 58\n");}
void fillerFunc59(){printf("Filler line 59\n");}
void fillerFunc60(){printf("Filler line 60\n");}
void fillerFunc61(){printf("Filler line 61\n");}
void fillerFunc62(){printf("Filler line 62\n");}
void fillerFunc63(){printf("Filler line 63\n");}
void fillerFunc64(){printf("Filler line 64\n");}
void fillerFunc65(){printf("Filler line 65\n");}
void fillerFunc66(){printf("Filler line 66\n");}
void fillerFunc67(){printf("Filler line 67\n");}
void fillerFunc68(){printf("Filler line 68\n");}
void fillerFunc69(){printf("Filler line 69\n");}
void fillerFunc70(){printf("Filler line 70\n");}
void fillerFunc71(){printf("Filler line 71\n");}
void fillerFunc72(){printf("Filler line 72\n");}
void fillerFunc73(){printf("Filler line 73\n");}
void fillerFunc74(){printf("Filler line 74\n");}
void fillerFunc75(){printf("Filler line 75\n");}
void fillerFunc76(){printf("Filler line 76\n");}
void fillerFunc77(){printf("Filler line 77\n");}
void fillerFunc78(){printf("Filler line 78\n");}
void fillerFunc79(){printf("Filler line 79\n");}
void fillerFunc80(){printf("Filler line 80\n");}
void fillerFunc81(){printf("Filler line 81\n");}
void fillerFunc82(){printf("Filler line 82\n");}
void fillerFunc83(){printf("Filler line 83\n");}
void fillerFunc84(){printf("Filler line 84\n");}
void fillerFunc85(){printf("Filler line 85\n");}
void fillerFunc86(){printf("Filler line 86\n");}
void fillerFunc87(){printf("Filler line 87\n");}
void fillerFunc88(){printf("Filler line 88\n");}
void fillerFunc89(){printf("Filler line 89\n");}
void fillerFunc90(){printf("Filler line 90\n");}
void fillerFunc91(){printf("Filler line 91\n");}
void fillerFunc92(){printf("Filler line 92\n");}
void fillerFunc93(){printf("Filler line 93\n");}
void fillerFunc94(){printf("Filler line 94\n");}
void fillerFunc95(){printf("Filler line 95\n");}
void fillerFunc96(){printf("Filler line 96\n");}
void fillerFunc97(){printf("Filler line 97\n");}
void fillerFunc98(){printf("Filler line 98\n");}
void fillerFunc99(){printf("Filler line 99\n");}
void fillerFunc100(){printf("Filler line 100\n");}
void fillerFunc101(){printf("Filler line 101\n");}
void fillerFunc102(){printf("Filler line 102\n");}
void fillerFunc103(){printf("Filler line 103\n");}
void fillerFunc104(){printf("Filler line 104\n");}
void fillerFunc105(){printf("Filler line 105\n");}
void fillerFunc106(){printf("Filler line 106\n");}
void fillerFunc107(){printf("Filler line 107\n");}
void fillerFunc108(){printf("Filler line 108\n");}
void fillerFunc109(){printf("Filler line 109\n");}
void fillerFunc110(){printf("Filler line 110\n");}
void fillerFunc111(){printf("Filler line 111\n");}
void fillerFunc112(){printf("Filler line 112\n");}
void fillerFunc113(){printf("Filler line 113\n");}
void fillerFunc114(){printf("Filler line 114\n");}
void fillerFunc115(){printf("Filler line 115\n");}
void fillerFunc116(){printf("Filler line 116\n");}
void fillerFunc117(){printf("Filler line 117\n");}
void fillerFunc118(){printf("Filler line 118\n");}
void fillerFunc119(){printf("Filler line 119\n");}
void fillerFunc120(){printf("Filler line 120\n");}
void fillerFunc121(){printf("Filler line 121\n");}
void fillerFunc122(){printf("Filler line 122\n");}
void fillerFunc123(){printf("Filler line 123\n");}
void fillerFunc124(){printf("Filler line 124\n");}
void fillerFunc125(){printf("Filler line 125\n");}
void fillerFunc126(){printf("Filler line 126\n");}
void fillerFunc127(){printf("Filler line 127\n");}
void fillerFunc128(){printf("Filler line 128\n");}
void fillerFunc129(){printf("Filler line 129\n");}
void fillerFunc130(){printf("Filler line 130\n");}
void fillerFunc131(){printf("Filler line 131\n");}
void fillerFunc132(){printf("Filler line 132\n");}
void fillerFunc133(){printf("Filler line 133\n");}
void fillerFunc134(){printf("Filler line 134\n");}
void fillerFunc135(){printf("Filler line 135\n");}
void fillerFunc136(){printf("Filler line 136\n");}
void fillerFunc137(){printf("Filler line 137\n");}
void fillerFunc138(){printf("Filler line 138\n");}
void fillerFunc139(){printf("Filler line 139\n");}
void fillerFunc140(){printf("Filler line 140\n");}
void fillerFunc141(){printf("Filler line 141\n");}
void fillerFunc142(){printf("Filler line 142\n");}
void fillerFunc143(){printf("Filler line 143\n");}
void fillerFunc144(){printf("Filler line 144\n");}
void fillerFunc145(){printf("Filler line 145\n");}
void fillerFunc146(){printf("Filler line 146\n");}
void fillerFunc147(){printf("Filler line 147\n");}
void fillerFunc148(){printf("Filler line 148\n");}
void fillerFunc149(){printf("Filler line 149\n");}
void fillerFunc150(){printf("Filler line 150\n");}
void fillerFunc151(){printf("Filler line 151\n");}
void fillerFunc152(){printf("Filler line 152\n");}
void fillerFunc153(){printf("Filler line 153\n");}
void fillerFunc154(){printf("Filler line 154\n");}
void fillerFunc155(){printf("Filler line 155\n");}
void fillerFunc156(){printf("Filler line 156\n");}
void fillerFunc157(){printf("Filler line 157\n");}
void fillerFunc158(){printf("Filler line 158\n");}
void fillerFunc159(){printf("Filler line 159\n");}
void fillerFunc160(){printf("Filler line 160\n");}
void fillerFunc161(){printf("Filler line 161\n");}
void fillerFunc162(){printf("Filler line 162\n");}
void fillerFunc163(){printf("Filler line 163\n");}
void fillerFunc164(){printf("Filler line 164\n");}
void fillerFunc165(){printf("Filler line 165\n");}
void fillerFunc166(){printf("Filler line 166\n");}
void fillerFunc167(){printf("Filler line 167\n");}
void fillerFunc168(){printf("Filler line 168\n");}
void fillerFunc169(){printf("Filler line 169\n");}
void fillerFunc170(){printf("Filler line 170\n");}
void fillerFunc171(){printf("Filler line 171\n");}
void fillerFunc172(){printf("Filler line 172\n");}
void fillerFunc173(){printf("Filler line 173\n");}
void fillerFunc174(){printf("Filler line 174\n");}
void fillerFunc175(){printf("Filler line 175\n");}
void fillerFunc176(){printf("Filler line 176\n");}
void fillerFunc177(){printf("Filler line 177\n");}
void fillerFunc178(){printf("Filler line 178\n");}
void fillerFunc179(){printf("Filler line 179\n");}
void fillerFunc180(){printf("Filler line 180\n");}
void fillerFunc181(){printf("Filler line 181\n");}
void fillerFunc182(){printf("Filler line 182\n");}
void fillerFunc183(){printf("Filler line 183\n");}
void fillerFunc184(){printf("Filler line 184\n");}
void fillerFunc185(){printf("Filler line 185\n");}
void fillerFunc186(){printf("Filler line 186\n");}
void fillerFunc187(){printf("Filler line 187\n");}
void fillerFunc188(){printf("Filler line 188\n");}
void fillerFunc189(){printf("Filler line 189\n");}
void fillerFunc190(){printf("Filler line 190\n");}
void fillerFunc191(){printf("Filler line 191\n");}
void fillerFunc192(){printf("Filler line 192\n");}
void fillerFunc193(){printf("Filler line 193\n");}
void fillerFunc194(){printf("Filler line 194\n");}
void fillerFunc195(){printf("Filler line 195\n");}
void fillerFunc196(){printf("Filler line 196\n");}
void fillerFunc197(){printf("Filler line 197\n");}
void fillerFunc198(){printf("Filler line 198\n");}
void fillerFunc199(){printf("Filler line 199\n");}
void fillerFunc200(){printf("Filler line 200\n");}
void fillerFunc201(){printf("Filler line 201\n");}
void fillerFunc202(){printf("Filler line 202\n");}
void fillerFunc203(){printf("Filler line 203\n");}
void fillerFunc204(){printf("Filler line 204\n");}
void fillerFunc205(){printf("Filler line 205\n");}
void fillerFunc206(){printf("Filler line 206\n");}
void fillerFunc207(){printf("Filler line 207\n");}
void fillerFunc208(){printf("Filler line 208\n");}
void fillerFunc209(){printf("Filler line 209\n");}
void fillerFunc210(){printf("Filler line 210\n");}
void fillerFunc211(){printf("Filler line 211\n");}
void fillerFunc212(){printf("Filler line 212\n");}
void fillerFunc213(){printf("Filler line 213\n");}
void fillerFunc214(){printf("Filler line 214\n");}
void fillerFunc215(){printf("Filler line 215\n");}
void fillerFunc216(){printf("Filler line 216\n");}
void fillerFunc217(){printf("Filler line 217\n");}
void fillerFunc218(){printf("Filler line 218\n");}
void fillerFunc219(){printf("Filler line 219\n");}
void fillerFunc220(){printf("Filler line 220\n");}
void fillerFunc221(){printf("Filler line 221\n");}
void fillerFunc222(){printf("Filler line 222\n");}
void fillerFunc223(){printf("Filler line 223\n");}
void fillerFunc224(){printf("Filler line 224\n");}
void fillerFunc225(){printf("Filler line 225\n");}
void fillerFunc226(){printf("Filler line 226\n");}
void fillerFunc227(){printf("Filler line 227\n");}
void fillerFunc228(){printf("Filler line 228\n");}
void fillerFunc229(){printf("Filler line 229\n");}
void fillerFunc230(){printf("Filler line 230\n");}
void fillerFunc231(){printf("Filler line 231\n");}
void fillerFunc232(){printf("Filler line 232\n");}
void fillerFunc233(){printf("Filler line 233\n");}
void fillerFunc234(){printf("Filler line 234\n");}
void fillerFunc235(){printf("Filler line 235\n");}
void fillerFunc236(){printf("Filler line 236\n");}
void fillerFunc237(){printf("Filler line 237\n");}
void fillerFunc238(){printf("Filler line 238\n");}
void fillerFunc239(){printf("Filler line 239\n");}
void fillerFunc240(){printf("Filler line 240\n");}
void fillerFunc241(){printf("Filler line 241\n");}
void fillerFunc242(){printf("Filler line 242\n");}
void fillerFunc243(){printf("Filler line 243\n");}
void fillerFunc244(){printf("Filler line 244\n");}
void fillerFunc245(){printf("Filler line 245\n");}
void fillerFunc246(){printf("Filler line 246\n");}
void fillerFunc247(){printf("Filler line 247\n");}
void fillerFunc248(){printf("Filler line 248\n");}
void fillerFunc249(){printf("Filler line 249\n");}
void fillerFunc250(){printf("Filler line 250\n");}
void fillerFunc251(){printf("Filler line 251\n");}
void fillerFunc252(){printf("Filler line 252\n");}
void fillerFunc253(){printf("Filler line 253\n");}
void fillerFunc254(){printf("Filler line 254\n");}
void fillerFunc255(){printf("Filler line 255\n");}
void fillerFunc256(){printf("Filler line 256\n");}
void fillerFunc257(){printf("Filler line 257\n");}
void fillerFunc258(){printf("Filler line 258\n");}
void fillerFunc259(){printf("Filler line 259\n");}
void fillerFunc260(){printf("Filler line 260\n");}
void fillerFunc261(){printf("Filler line 261\n");}
void fillerFunc262(){printf("Filler line 262\n");}
void fillerFunc263(){printf("Filler line 263\n");}
void fillerFunc264(){printf("Filler line 264\n");}
void fillerFunc265(){printf("Filler line 265\n");}
void fillerFunc266(){printf("Filler line 266\n");}
void fillerFunc267(){printf("Filler line 267\n");}
void fillerFunc268(){printf("Filler line 268\n");}
void fillerFunc269(){printf("Filler line 269\n");}
void fillerFunc270(){printf("Filler line 270\n");}
void fillerFunc271(){printf("Filler line 271\n");}
void fillerFunc272(){printf("Filler line 272\n");}
void fillerFunc273(){printf("Filler line 273\n");}
void fillerFunc274(){printf("Filler line 274\n");}
void fillerFunc275(){printf("Filler line 275\n");}
void fillerFunc276(){printf("Filler line 276\n");}
void fillerFunc277(){printf("Filler line 277\n");}
void fillerFunc278(){printf("Filler line 278\n");}
void fillerFunc279(){printf("Filler line 279\n");}
void fillerFunc280(){printf("Filler line 280\n");}
void fillerFunc281(){printf("Filler line 281\n");}
void fillerFunc282(){printf("Filler line 282\n");}
void fillerFunc283(){printf("Filler line 283\n");}
void fillerFunc284(){printf("Filler line 284\n");}
void fillerFunc285(){printf("Filler line 285\n");}
void fillerFunc286(){printf("Filler line 286\n");}
void fillerFunc287(){printf("Filler line 287\n");}
void fillerFunc288(){printf("Filler line 288\n");}
void fillerFunc289(){printf("Filler line 289\n");}
void fillerFunc290(){printf("Filler line 290\n");}
void fillerFunc291(){printf("Filler line 291\n");}
void fillerFunc292(){printf("Filler line 292\n");}
void fillerFunc293(){printf("Filler line 293\n");}
void fillerFunc294(){printf("Filler line 294\n");}
void fillerFunc295(){printf("Filler line 295\n");}
void fillerFunc296(){printf("Filler line 296\n");}
void fillerFunc297(){printf("Filler line 297\n");}
void fillerFunc298(){printf("Filler line 298\n");}
void fillerFunc299(){printf("Filler line 299\n");}